services:
  campusevents:
   
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ConnectionStrings__DefaultConnection=Host=postgres-db;Port=5432;Database=CampusEventsManager;Username=postgres;Password=secret
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/Campus-Events.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=QQ2024docker
    ports:
      - "8081"
    volumes:
      - ./CampusEvents/Campus-Events.pfx:/https/Campus-Events.pfx:ro
