version: '3.8'

services:
  campusevents:
    image: campusevents
    build:
      context: .
      dockerfile: CampusEvents/Dockerfile
    depends_on:
      - postgres-db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/Campus-Events.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=QQ2024docker
      - ConnectionStrings__DefaultConnection=Host=postgres-db;Port=5432;Database=CampusEventsManager;Username=postgres;Password=secret

  postgres-db:
    image: postgres:16.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: CampusEventsManager
    ports:
      - "5432:5432"

    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: 

networks:
  default:
    name: dockercompose16039205016906870231_default"